# Generated by Django 4.0.2 on 2022-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerupdate',
            fields=[
                ('farmerupdate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=100)),
                ('items', models.CharField(default='', max_length=500)),
                ('weight', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='farmer/images')),
            ],
        ),
    ]
