# Generated by Django 4.0.2 on 2022-03-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homekart', '0003_alter_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='namet',
        ),
    ]
