# Generated by Django 4.0.2 on 2022-03-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homekart', '0004_rename_name_contact_namet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='namet',
            new_name='name',
        ),
    ]
